[package]
name = "note-boi"
version = "0.1.0"
description = "A Notes App"
authors = ["Daniel Knights"]
license = "MIT"
repository = "https://github.com/Daniel-Knights/note-boi"
default-run = "note-boi"
edition = "2021"
build = "build.rs"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-rc", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-rc", features = ["shell-open"] }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/tauri-plugin-window-state", branch = "release" }
uuid = { version = "0.8", features = ["v4"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
